### ISSUE TITLE
candle stick chart

### ISSUE THREAD

**Issue by miladheydari** [hi-manshu/Charty#15]
please add candle stick chart

**Comment by hi-manshu** [comment]
We will be adding it soon!

**Comment by hi-manshu** [comment]
Hey @miladheydari 
I created the candle chart . Please do try and let me know
https://github.com/hi-manshu/Charty/releases/tag/v1.1.3-alpha04

**Comment by CarlosEsco** [comment]
> Hey @miladheydari I created the candle chart . Please do try and let me know https://github.com/hi-manshu/Charty/releases/tag/v1.1.3-alpha04

Looks like there was an issue uploading again, unable to pull alpha04.

**Comment by hi-manshu** [comment]
Can you check it once more, Its working for me!

**Comment by CarlosEsco** [comment]
> Can you check it once more, Its working for me!

seems good now.  Must have been a weird blip.  I tried pulling and I checked maven central and it wasn't there.
