### ISSUE TITLE
Optional drawXLabel and zero-based first and last line

### ISSUE THREAD

**Issue by michaelnimbs** [hi-manshu/Charty#25]
![charty](https://user-images.githubusercontent.com/28657743/186662052-0ecd75df-e1fd-4b59-972e-982ffb87e650.png)

LineChart:
Please make the call to `drawXLabel `configurable as well as the first and last line from and back to zero, that does not correspond to any of my LineData (`moveTo(0f, size.height)` and `path.lineTo(size.width, size.height)`).

Thank you for the library.

**Comment by hi-manshu** [comment]
Hey, what would you want here then? What should happen for the last value?

**Comment by michaelnimbs** [comment]
Just the last value and the line ends but not the line from last value to zero.
In your sample app this would look like this:

![charty_sample](https://user-images.githubusercontent.com/28657743/186669125-d82dc8ae-f2f8-4530-8a13-4ec44135f914.png)

**Comment by hi-manshu** [comment]
Understood.Will fix it. Thanks.

**Comment by hi-manshu** [comment]
When you say make x-axis label configurable? What we mean by it here?

**Comment by hi-manshu** [comment]
Hey @michaelnimbs ,
Thank you for pointing this to me. I have added that in new release in `1.1.0-alpha02` Please do check!

**Comment by michaelnimbs** [comment]
@hi-manshu thank you for the quick release, the lines are drawn correctly now.

I would like to disable the x-axis labels, an if-statement around `drawXLabel(data, centerOffset, radius, lineData.count())`.
I have around 200 measurements with timestamps as x value and a range slider for zooming in. So as you can see in the image it doesn't make any sense to show them there.

![charty_zoom](https://user-images.githubusercontent.com/28657743/186867744-079b7723-d15b-4010-802b-dd7a61af4361.png)

**Comment by hi-manshu** [comment]
Sure, definitely make sense. Let me see if I can do a quick fix

**Comment by hi-manshu** [comment]
Hey @michaelnimbs ,
Fixed the request for you. Check the new Readme

**Comment by michaelnimbs** [comment]
@hi-manshu Works great, thank you!

**Comment by hi-manshu** [comment]
Amazing buddy! Thank you for following up. Looking forward for more
feedback
