### ISSUE TITLE
The CurveLineChart does not display xlabels

### ISSUE THREAD

**Issue by afoolzh** [hi-manshu/Charty#29]
The CurveLineChart does not display xlabels

**Comment by hi-manshu** [comment]
Hey @afoolzh ,
Thank you for opening this. You can find this release here.
https://github.com/hi-manshu/Charty/releases/tag/1.1.2-alpha02

Closing this now, but if you find this useful, please feel free to drop a star and share with other devs

**Comment by morarafrank** [comment]
I'm using this latest version and still it's not able to display x-axis labels.
