### ISSUE TITLE
Pie chart Donut doesn't always "touch"

### ISSUE THREAD

**Issue by CarlosEsco** [hi-manshu/Charty#35]
See picture below
![image](https://user-images.githubusercontent.com/2092019/189196060-26087a28-a211-4e54-8f44-5965ec39472a.png)

data for this was 3,1,1.  Happens with and without expandDonutOnClick enabled

It's not an issue for non donut
![image](https://user-images.githubusercontent.com/2092019/189196327-c6b17921-de9b-4a8a-830e-763e890b099b.png)

**Comment by hi-manshu** [comment]
Hey @CarlosEsco ,
What is the issue here? I cannot imagine. Can you elaborate a bit more?

**Comment by CarlosEsco** [comment]
Notice in the donut the visual gap between the pie items?  It only happens in certain scenarios.

**Comment by hi-manshu** [comment]
Understood. I will try it as well. I thought by touch you meant "click". Let me try this out

**Comment by hi-manshu** [comment]
Hey Hey @CarlosEsco ,
Please check this https://github.com/hi-manshu/Charty/releases/tag/v1.1.3-alpha03
and let me know if this fixed.

**Comment by CarlosEsco** [comment]
looks good thanks!
