### ISSUE TITLE
Need the ability to set LineChart label color

### ISSUE THREAD

**Issue by CarlosEsco** [hi-manshu/Charty#39]

**Comment by hi-manshu** [comment]
hey thanks for opening this. I will do it but my priority as have to add few more charts in here

**Comment by CarlosEsco** [comment]
Understandable. The main issue currently is any chart with labels is unusable on a dark theme since the text is black.

**Comment by hi-manshu** [comment]
Def! I see your point. I will make sure to get back to this ASAP!
And thank you @CarlosEsco for all the insights. They are really useful

**Comment by hi-manshu** [comment]
You can find this in the next release!
