### ISSUE TITLE
Labels not visible on dark mode

### ISSUE THREAD

**Issue by sanskar10100** [hi-manshu/Charty#45]
Using a `LineChart`, the x and y-axis labels aren't legible on dark mode since they are in black color. The axis config colors aren't applied to them.

```kotlin
LineChart(
            lineData = minutesReadData,
            color = MaterialTheme.colors.primaryVariant,
            modifier = modifier
                .height(250.dp)
                .fillMaxWidth()
                .padding(vertical = 32.dp, horizontal = 32.dp),
            axisConfig = AxisConfig(
                showAxis = true,
                isAxisDashed = false,
                showUnitLabels = true,
                showXLabels = true,
                xAxisColor = Color.White,
                yAxisColor = Color.White,
            ),
        )
```

On Light Mode:
![image](https://user-images.githubusercontent.com/22092047/191969746-97fc3905-fb3f-40ab-af90-0b94dea88cf9.png)

On Dark Mode:
![image](https://user-images.githubusercontent.com/22092047/191969872-38f03878-060c-44f8-b19f-e46a00a51aa5.png)

**Comment by hi-manshu** [comment]
Hey this is something I have planned for future releases but right now I am focusing more on making this library stable.. but will keep this in mind!

**Comment by sanskar10100** [comment]
Late addition:

As a workaround, I forked the lib and obtained the `onSurface` color in the `LineChart` composable:
```kotlin
val labelColor = MaterialTheme.colors.onSurface
yAxis(... labelColor = labelColor)
```

Then, added a color param to `DrawScope.yAxis` and `DrawScope.drawXLabel` which is then consumed during paint object init:
```kotlin
fun draw...(..., labelColor: Color = Color.Black) {
    // ...
    Paint().apply {
        // ...
        color = labelColor.toArgb()
    }
}
```

Now,
![image](https://user-images.githubusercontent.com/22092047/193568970-4a5f727f-6ba9-4543-a94f-a992ef28777d.png) ![image](https://user-images.githubusercontent.com/22092047/193569001-95d9b89d-1229-4d8f-951a-1ddc456b901c.png)

**Comment by hi-manshu** [comment]
Hey, I have these fixed, Will be putting a new release soon!

**Comment by hi-manshu** [comment]
This will be fixed in the next release
