### ISSUE TITLE
Add demo APK link

### ISSUE THREAD

**Issue by yogeshpaliyal** [hi-manshu/Charty#9]
Add demo apk link in readme file and that should be updated on each release.

**Comment by yogeshpaliyal** [comment]
Hey @hi-manshu I want to work on this.

**Comment by hi-manshu** [comment]
Please do it, I already have the app lined up but need actions to be integrated.

**Comment by yogeshpaliyal** [comment]
@hi-manshu I think we can reopen this, because the last chages are in main-old branch.
